[[redirects]]
  from = "/accueil"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/admin"
  to = "/admin.html"
  status = 200

[[redirects]]
  from = "/connexion"
  to = "/connexion.html"
  status = 200

[[redirects]]
  from = "/inscription"
  to = "/inscription.html"
  status = 200

[[redirects]]
  from = "/profil"
  to = "/profil.html"
  status = 200

[[redirects]]
  from = "/detail"
  to = "/detail.html"
  status = 200

[[redirects]]
  from = "/liste_livres"
  to = "/liste_livres.html"
  status = 200

[[redirects]]
  from = "/demande_pret"
  to = "/demande_pret.html"
  status = 200

[[redirects]]
  from = "/auteur"
  to = "/auteur.html"
  status = 200


[[redirects]]
  from = "/*"
  to = "/404.html"
  status = 404